import z from "zod";

 const ServiceCode = {
  BINANCE: 'BINANCE',
  BYBIT: 'BYBIT',
  KRAKEN: 'KRAKEN',
  TELEGRAM: 'TELEGRAM',
  EMAIL: 'EMAIL',
  DISCORD_WEBHOOKS: 'DISCORD_WEBHOOKS',
  SLACK_WEBHOOKS: 'SLACK_WEBHOOKS',
  SMS_TWILIO: 'SMS_TWILIO',
  PUSH_NOTIFICATIONS_ONESIGNAL: 'PUSH_NOTIFICATIONS_ONESIGNAL',
  WHATSAPP_BUSINESS: 'WHATSAPP_BUSINESS',
  WEBHOOKS: 'WEBHOOKS',
} as const;

export const ServiceCodeSchema = z.nativeEnum(ServiceCode);