/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Trading Bot API
 * API for trading bot user management and authentication
 * OpenAPI spec version: 1.0
 */
import type { CreateUserDto } from '.././';

import { customInstance } from '../../api/mutator';

/**
 * @summary Create a user
 */
export type usersApiControllerCreateUserResponse201 = {
  data: void;
  status: 201;
};

export type usersApiControllerCreateUserResponseSuccess =
  usersApiControllerCreateUserResponse201 & {
    headers: Headers;
  };
export type usersApiControllerCreateUserResponse =
  usersApiControllerCreateUserResponseSuccess;

export const getUsersApiControllerCreateUserUrl = () => {
  return `/api/v1/users`;
};

export const usersApiControllerCreateUser = async (
  createUserDto: CreateUserDto,
  options?: RequestInit
): Promise<usersApiControllerCreateUserResponse> => {
  return customInstance<usersApiControllerCreateUserResponse>(
    getUsersApiControllerCreateUserUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(createUserDto),
    }
  );
};
