#version: '3.8'

name: ${DOCKER_PROJECT_NAME}

services:
  postgres:
    image: postgres:16
    restart: always
    container_name: ${DOCKER_PROJECT_NAME}-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    profiles:
      - development
      - api-service
      - external
      - init-external
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ${DOCKER_DB_VOLUME}:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: ${DOCKER_PROJECT_NAME}-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASSWORD}
    profiles:
      - development
      - api-service
      - external
      - init-external
    ports:
      - "${RMQ_PORT}:5672"
      - "${RMQ_MANAGEMENT_PORT}:15672"
    volumes:
      - ${DOCKER_RMQ_VOLUME}:/var/lib/rabbitmq

  auto-trader:
    build:
      context: .
      dockerfile: apps/auto-trader/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    profiles:
      - development

