#version: '3.8'

name: ${DOCKER_PROJECT_NAME:-trading_assist}

x-postgres-common: &postgres-common
  image: postgres:16
  restart: always
  environment:
    POSTGRES_USER: ${DB_USER}
    POSTGRES_PASSWORD: ${DB_PASSWORD}
    POSTGRES_DB: ${DB_NAME}
  ports:
    - "${DB_PORT}:5432"

x-db-env: &db-env
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_NAME: ${DB_NAME}

services:
  postgres:
    <<: *postgres-common
    container_name: ${DOCKER_PROJECT_NAME:-trading_assist}-postgres
    profiles:
      - development
      - api-service
      - external
      - init-external
    volumes:
      - ${DOCKER_DB_VOLUME}:/var/lib/postgresql/data
    networks:
      - trading_bot_network

  auto-trader:
    build:
      context: .
      dockerfile: apps/auto-trader/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      <<: *db-env
    profiles:
      - development
    networks:
      - trading_bot_network
networks:
  trading_bot_network:
    driver: bridge
