// TODO file generated by AI. Should be checked if we can avoid using of it.

import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'libs/models/prisma/schema.prisma',
  migrations: {
    path: 'libs/models/prisma/migrations',
  },
  datasource: {
    url: process.env.DB_URL,
  },
});
