// TODO file generated by AI. Should be checked if we can avoid using of it.

import { defineConfig } from 'prisma/config';

export default defineConfig({
  datasource: {
    url: process.env.DB_URL,
  },
});
