const orders = [
    {
      orderId: 3728564645,
      symbol: 'NKNUSDT',
      status: 'FILLED',
      clientOrderId: 'android_pqjdUF5EXME4b9CMpRgV',
      price: '0',
      avgPrice: '0.12411',
      origQty: '806',
      executedQty: '806',
      cumQuote: '100.03266',
      timeInForce: 'GTC',
      type: 'MARKET',
      reduceOnly: false,
      closePosition: false,
      side: 'BUY',
      positionSide: 'BOTH',
      stopPrice: '0',
      workingType: 'CONTRACT_PRICE',
      priceMatch: 'NONE',
      selfTradePreventionMode: 'NONE',
      goodTillDate: 0,
      priceProtect: false,
      origType: 'MARKET',
      time: 1717702679982,
      updateTime: 1717702679982
    },
    {
      orderId: 3729338861,
      symbol: 'NKNUSDT',
      status: 'FILLED',
      clientOrderId: 'android_xMi1erxOELUxnXxlvuWY',
      price: '0',
      avgPrice: '0.12560',
      origQty: '795',
      executedQty: '795',
      cumQuote: '99.85514',
      timeInForce: 'GTC',
      type: 'MARKET',
      reduceOnly: true,
      closePosition: false,
      side: 'SELL',
      positionSide: 'BOTH',
      stopPrice: '0',
      workingType: 'CONTRACT_PRICE',
      priceMatch: 'NONE',
      selfTradePreventionMode: 'NONE',
      goodTillDate: 0,
      priceProtect: false,
      origType: 'MARKET',
      time: 1717739158334,
      updateTime: 1717739158334
    },
    {
      orderId: 3729903500,
      symbol: 'NKNUSDT',
      status: 'FILLED',
      clientOrderId: 'android_cllBknYUD7zbHl0oaOaO',
      price: '0',
      avgPrice: '0.12462',
      origQty: '4012',
      executedQty: '4012',
      cumQuote: '499.97363',
      timeInForce: 'GTC',
      type: 'MARKET',
      reduceOnly: false,
      closePosition: false,
      side: 'BUY',
      positionSide: 'BOTH',
      stopPrice: '0',
      workingType: 'CONTRACT_PRICE',
      priceMatch: 'NONE',
      selfTradePreventionMode: 'NONE',
      goodTillDate: 0,
      priceProtect: false,
      origType: 'MARKET',
      time: 1717763738821,
      updateTime: 1717763738821
    },
    {
      orderId: 3729974407,
      symbol: 'NKNUSDT',
      status: 'FILLED',
      clientOrderId: 'android_nstLgaIzNAelF5PgSbOf',
      price: '0',
      avgPrice: '0.12550',
      origQty: '3984',
      executedQty: '3984',
      cumQuote: '499.98773',
      timeInForce: 'GTC',
      type: 'MARKET',
      reduceOnly: false,
      closePosition: false,
      side: 'SELL',
      positionSide: 'BOTH',
      stopPrice: '0',
      workingType: 'CONTRACT_PRICE',
      priceMatch: 'NONE',
      selfTradePreventionMode: 'NONE',
      goodTillDate: 0,
      priceProtect: false,
      origType: 'MARKET',
      time: 1717765087258,
      updateTime: 1717765087258
    },
    {
      orderId: 3730669480,
      symbol: 'NKNUSDT',
      status: 'FILLED',
      clientOrderId: 'android_NOifGmnBkRNB2A5hNUm8',
      price: '0',
      avgPrice: '0.11008',
      origQty: '4520',
      executedQty: '4520',
      cumQuote: '497.54128',
      timeInForce: 'GTC',
      type: 'MARKET',
      reduceOnly: false,
      closePosition: false,
      side: 'BUY',
      positionSide: 'BOTH',
      stopPrice: '0',
      workingType: 'CONTRACT_PRICE',
      priceMatch: 'NONE',
      selfTradePreventionMode: 'NONE',
      goodTillDate: 0,
      priceProtect: false,
      origType: 'MARKET',
      time: 1717783492796,
      updateTime: 1717783493687
    },
    {
      orderId: 3730779603,
      symbol: 'NKNUSDT',
      status: 'FILLED',
      clientOrderId: 'android_mPdLJ9GfNHrK5fLhlAVN',
      price: '0',
      avgPrice: '0.11133',
      origQty: '4489',
      executedQty: '4489',
      cumQuote: '499.76430',
      timeInForce: 'GTC',
      type: 'MARKET',
      reduceOnly: true,
      closePosition: false,
      side: 'SELL',
      positionSide: 'BOTH',
      stopPrice: '0',
      workingType: 'CONTRACT_PRICE',
      priceMatch: 'NONE',
      selfTradePreventionMode: 'NONE',
      goodTillDate: 0,
      priceProtect: false,
      origType: 'MARKET',
      time: 1717784583458,
      updateTime: 1717784583458
    },
    {
      orderId: 3732358751,
      symbol: 'NKNUSDT',
      status: 'FILLED',
      clientOrderId: 'android_s5cEQ3662EbPaaVbbrqf',
      price: '0',
      avgPrice: '0.10939',
      origQty: '913',
      executedQty: '913',
      cumQuote: '99.87156',
      timeInForce: 'GTC',
      type: 'MARKET',
      reduceOnly: false,
      closePosition: false,
      side: 'BUY',
      positionSide: 'BOTH',
      stopPrice: '0',
      workingType: 'CONTRACT_PRICE',
      priceMatch: 'NONE',
      selfTradePreventionMode: 'NONE',
      goodTillDate: 0,
      priceProtect: false,
      origType: 'MARKET',
      time: 1717846865135,
      updateTime: 1717846865135
    },
    {
      orderId: 3732512151,
      symbol: 'NKNUSDT',
      status: 'FILLED',
      clientOrderId: 'android_L0juQs4WolmD3xQYtriH',
      price: '0',
      avgPrice: '0.10769',
      origQty: '928',
      executedQty: '928',
      cumQuote: '99.93478',
      timeInForce: 'GTC',
      type: 'MARKET',
      reduceOnly: false,
      closePosition: false,
      side: 'BUY',
      positionSide: 'BOTH',
      stopPrice: '0',
      workingType: 'CONTRACT_PRICE',
      priceMatch: 'NONE',
      selfTradePreventionMode: 'NONE',
      goodTillDate: 0,
      priceProtect: false,
      origType: 'MARKET',
      time: 1717851155743,
      updateTime: 1717851155743
    },
    {
      orderId: 3732594542,
      symbol: 'NKNUSDT',
      status: 'FILLED',
      clientOrderId: 'android_vE785UO7SKqilZkk5PMH',
      price: '0',
      avgPrice: '0.10613',
      origQty: '942',
      executedQty: '942',
      cumQuote: '99.97452',
      timeInForce: 'GTC',
      type: 'MARKET',
      reduceOnly: false,
      closePosition: false,
      side: 'BUY',
      positionSide: 'BOTH',
      stopPrice: '0',
      workingType: 'CONTRACT_PRICE',
      priceMatch: 'NONE',
      selfTradePreventionMode: 'NONE',
      goodTillDate: 0,
      priceProtect: false,
      origType: 'MARKET',
      time: 1717853134080,
      updateTime: 1717853134080
    },
    {
      orderId: 3732955913,
      symbol: 'NKNUSDT',
      status: 'FILLED',
      clientOrderId: 'android_NJDppeDVT92X8S3G3egY',
      price: '0',
      avgPrice: '0.10669',
      origQty: '937',
      executedQty: '937',
      cumQuote: '99.96853',
      timeInForce: 'GTC',
      type: 'MARKET',
      reduceOnly: false,
      closePosition: false,
      side: 'BUY',
      positionSide: 'BOTH',
      stopPrice: '0',
      workingType: 'CONTRACT_PRICE',
      priceMatch: 'NONE',
      selfTradePreventionMode: 'NONE',
      goodTillDate: 0,
      priceProtect: false,
      origType: 'MARKET',
      time: 1717865071081,
      updateTime: 1717865071081
    },
    {
      orderId: 3733121690,
      symbol: 'NKNUSDT',
      status: 'FILLED',
      clientOrderId: 'android_JwbLNdHpKHQAKYViDj6N',
      price: '0',
      avgPrice: '0.10731',
      origQty: '931',
      executedQty: '931',
      cumQuote: '99.90174',
      timeInForce: 'GTC',
      type: 'MARKET',
      reduceOnly: true,
      closePosition: false,
      side: 'SELL',
      positionSide: 'BOTH',
      stopPrice: '0',
      workingType: 'CONTRACT_PRICE',
      priceMatch: 'NONE',
      selfTradePreventionMode: 'NONE',
      goodTillDate: 0,
      priceProtect: false,
      origType: 'MARKET',
      time: 1717870068909,
      updateTime: 1717870068909
    },
    {
      orderId: 3734160257,
      symbol: 'NKNUSDT',
      status: 'FILLED',
      clientOrderId: 'android_mAUQm4WX9b43KUc7WCeN',
      price: '0',
      avgPrice: '0.10734',
      origQty: '931',
      executedQty: '931',
      cumQuote: '99.93182',
      timeInForce: 'GTC',
      type: 'MARKET',
      reduceOnly: true,
      closePosition: false,
      side: 'SELL',
      positionSide: 'BOTH',
      stopPrice: '0',
      workingType: 'CONTRACT_PRICE',
      priceMatch: 'NONE',
      selfTradePreventionMode: 'NONE',
      goodTillDate: 0,
      priceProtect: false,
      origType: 'MARKET',
      time: 1717918956368,
      updateTime: 1717918956368
    },
    {
      orderId: 3734511348,
      symbol: 'NKNUSDT',
      status: 'FILLED',
      clientOrderId: 'android_N9dfy2im3dn3k18DjJ2q',
      price: '0',
      avgPrice: '0.10825',
      origQty: '923',
      executedQty: '923',
      cumQuote: '99.91138',
      timeInForce: 'GTC',
      type: 'MARKET',
      reduceOnly: true,
      closePosition: false,
      side: 'SELL',
      positionSide: 'BOTH',
      stopPrice: '0',
      workingType: 'CONTRACT_PRICE',
      priceMatch: 'NONE',
      selfTradePreventionMode: 'NONE',
      goodTillDate: 0,
      priceProtect: false,
      origType: 'MARKET',
      time: 1717937642531,
      updateTime: 1717937642531
    },
    {
      orderId: 3734823921,
      symbol: 'NKNUSDT',
      status: 'FILLED',
      clientOrderId: 'android_1R6NpDgSp28vhs3LZdDR',
      price: '0',
      avgPrice: '0.10716',
      origQty: '933',
      executedQty: '933',
      cumQuote: '99.98028',
      timeInForce: 'GTC',
      type: 'MARKET',
      reduceOnly: false,
      closePosition: false,
      side: 'BUY',
      positionSide: 'BOTH',
      stopPrice: '0',
      workingType: 'CONTRACT_PRICE',
      priceMatch: 'NONE',
      selfTradePreventionMode: 'NONE',
      goodTillDate: 0,
      priceProtect: false,
      origType: 'MARKET',
      time: 1717950804549,
      updateTime: 1717950804549
    },
    {
      orderId: 3734841827,
      symbol: 'NKNUSDT',
      status: 'FILLED',
      clientOrderId: 'android_49bjPD2ZzDPjTIWIQZbi',
      price: '0',
      avgPrice: '0.10697',
      origQty: '934',
      executedQty: '934',
      cumQuote: '99.90998',
      timeInForce: 'GTC',
      type: 'MARKET',
      reduceOnly: false,
      closePosition: false,
      side: 'BUY',
      positionSide: 'BOTH',
      stopPrice: '0',
      workingType: 'CONTRACT_PRICE',
      priceMatch: 'NONE',
      selfTradePreventionMode: 'NONE',
      goodTillDate: 0,
      priceProtect: false,
      origType: 'MARKET',
      time: 1717951812315,
      updateTime: 1717951812315
    },
    {
      orderId: 3734957296,
      symbol: 'NKNUSDT',
      status: 'FILLED',
      clientOrderId: 'android_yhYJ5mQVKUaMSI6weOYl',
      price: '0',
      avgPrice: '0.10682',
      origQty: '936',
      executedQty: '936',
      cumQuote: '99.98164',
      timeInForce: 'GTC',
      type: 'MARKET',
      reduceOnly: false,
      closePosition: false,
      side: 'BUY',
      positionSide: 'BOTH',
      stopPrice: '0',
      workingType: 'CONTRACT_PRICE',
      priceMatch: 'NONE',
      selfTradePreventionMode: 'NONE',
      goodTillDate: 0,
      priceProtect: false,
      origType: 'MARKET',
      time: 1717957238076,
      updateTime: 1717957238076
    },
    {
      orderId: 3734975625,
      symbol: 'NKNUSDT',
      status: 'FILLED',
      clientOrderId: 'android_wJ8ONTjwbmzsWGN82WMm',
      price: '0',
      avgPrice: '0.10702',
      origQty: '934',
      executedQty: '934',
      cumQuote: '99.95506',
      timeInForce: 'GTC',
      type: 'MARKET',
      reduceOnly: true,
      closePosition: false,
      side: 'SELL',
      positionSide: 'BOTH',
      stopPrice: '0',
      workingType: 'CONTRACT_PRICE',
      priceMatch: 'NONE',
      selfTradePreventionMode: 'NONE',
      goodTillDate: 0,
      priceProtect: false,
      origType: 'MARKET',
      time: 1717958048550,
      updateTime: 1717958048550
    },
    {
      orderId: 3735026561,
      symbol: 'NKNUSDT',
      status: 'FILLED',
      clientOrderId: 'android_65mYwixTjXUK3B55hSDl',
      price: '0',
      avgPrice: '0.10764',
      origQty: '2787',
      executedQty: '2787',
      cumQuote: '300.00571',
      timeInForce: 'GTC',
      type: 'MARKET',
      reduceOnly: true,
      closePosition: false,
      side: 'SELL',
      positionSide: 'BOTH',
      stopPrice: '0',
      workingType: 'CONTRACT_PRICE',
      priceMatch: 'NONE',
      selfTradePreventionMode: 'NONE',
      goodTillDate: 0,
      priceProtect: false,
      origType: 'MARKET',
      time: 1717960094562,
      updateTime: 1717960094562
    },
    {
      orderId: 3735133649,
      symbol: 'NKNUSDT',
      status: 'FILLED',
      clientOrderId: 'android_UcYypwMel78wLB8Ux0Lm',
      price: '0',
      avgPrice: '0.10723',
      origQty: '932',
      executedQty: '932',
      cumQuote: '99.93836',
      timeInForce: 'GTC',
      type: 'MARKET',
      reduceOnly: false,
      closePosition: false,
      side: 'BUY',
      positionSide: 'BOTH',
      stopPrice: '0',
      workingType: 'CONTRACT_PRICE',
      priceMatch: 'NONE',
      selfTradePreventionMode: 'NONE',
      goodTillDate: 0,
      priceProtect: false,
      origType: 'MARKET',
      time: 1717964870054,
      updateTime: 1717964870054
    },
    {
      orderId: 3736187167,
      symbol: 'NKNUSDT',
      status: 'FILLED',
      clientOrderId: 'android_mjzS4PIAAEXOtLqa39Fa',
      price: '0',
      avgPrice: '0.10620',
      origQty: '941',
      executedQty: '941',
      cumQuote: '99.93474',
      timeInForce: 'GTC',
      type: 'MARKET',
      reduceOnly: false,
      closePosition: false,
      side: 'BUY',
      positionSide: 'BOTH',
      stopPrice: '0',
      workingType: 'CONTRACT_PRICE',
      priceMatch: 'NONE',
      selfTradePreventionMode: 'NONE',
      goodTillDate: 0,
      priceProtect: false,
      origType: 'MARKET',
      time: 1718012459231,
      updateTime: 1718012459231
    },
    {
      orderId: 3736798555,
      symbol: 'NKNUSDT',
      status: 'FILLED',
      clientOrderId: 'android_OGzEWj0eDHi2eNwBQ6Up',
      price: '0',
      avgPrice: '0.10739',
      origQty: '1862',
      executedQty: '1862',
      cumQuote: '199.95169',
      timeInForce: 'GTC',
      type: 'MARKET',
      reduceOnly: true,
      closePosition: false,
      side: 'SELL',
      positionSide: 'BOTH',
      stopPrice: '0',
      workingType: 'CONTRACT_PRICE',
      priceMatch: 'NONE',
      selfTradePreventionMode: 'NONE',
      goodTillDate: 0,
      priceProtect: false,
      origType: 'MARKET',
      time: 1718035198194,
      updateTime: 1718035198194
    },
    {
      orderId: 3737291325,
      symbol: 'NKNUSDT',
      status: 'FILLED',
      clientOrderId: 'android_OjWuVMJCjdyX5PKUUPyg',
      price: '0',
      avgPrice: '0.10508',
      origQty: '951',
      executedQty: '951',
      cumQuote: '99.93040',
      timeInForce: 'GTC',
      type: 'MARKET',
      reduceOnly: false,
      closePosition: false,
      side: 'BUY',
      positionSide: 'BOTH',
      stopPrice: '0',
      workingType: 'CONTRACT_PRICE',
      priceMatch: 'NONE',
      selfTradePreventionMode: 'NONE',
      goodTillDate: 0,
      priceProtect: false,
      origType: 'MARKET',
      time: 1718051153914,
      updateTime: 1718051153914
    },
    {
      orderId: 3737589196,
      symbol: 'NKNUSDT',
      status: 'FILLED',
      clientOrderId: 'android_GTE26vVENFBt9Huytl0e',
      price: '0',
      avgPrice: '0.10452',
      origQty: '957',
      executedQty: '957',
      cumQuote: '100.02882',
      timeInForce: 'GTC',
      type: 'MARKET',
      reduceOnly: false,
      closePosition: false,
      side: 'BUY',
      positionSide: 'BOTH',
      stopPrice: '0',
      workingType: 'CONTRACT_PRICE',
      priceMatch: 'NONE',
      selfTradePreventionMode: 'NONE',
      goodTillDate: 0,
      priceProtect: false,
      origType: 'MARKET',
      time: 1718065647334,
      updateTime: 1718065647334
    }
];

const result = {
    currentPrice: '// Current price here',
    position: {
        // Position here
    },
    initialOffer: {
        // Initial Offer
    },
    history: [
        // List of orders
    ],
    profitPairs: [ // This should be fullfiled form 
        {
            open: {

            },
            close: {

            },
            profit: "// Profit in USDT"
        }
        // ....
    ],

}


console.log("orders.length =", orders.length);

let buyTotalPrice = 0;
let buyTotalQuantity = 0;
let averageBuyPrice = 0;

let sellTotalPrice = 0;
let sellTotalQuantity = 0;
let averageSellPrice = 0;


orders.forEach(item => {
    if (item.side === 'BUY'){
        buyTotalQuantity = buyTotalQuantity + parseFloat(item.executedQty);
        buyTotalPrice = buyTotalPrice + (parseFloat(item.avgPrice)*parseFloat(item.executedQty))
    }
    else if(item.side === 'SELL'){
        sellTotalQuantity = sellTotalQuantity + parseFloat(item.executedQty);
        sellTotalPrice = sellTotalPrice + (parseFloat(item.avgPrice)*parseFloat(item.executedQty))
    }
    else{
        console.log("How you are here????");
    }
});

console.log("buyTotalPrice =", buyTotalPrice);
console.log("buyTotalQuantity =", buyTotalQuantity);
console.log("averageBuy =", buyTotalPrice/ buyTotalQuantity)

console.log("sellTotalPrice =", sellTotalPrice);
console.log("sellTotalQuantity =", sellTotalQuantity);
console.log("averageSell =", sellTotalPrice/sellTotalQuantity)

console.log("difference = ", sellTotalPrice - buyTotalPrice);
console.log()