/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Trading Bot API
 * API for trading bot user management and authentication
 * OpenAPI spec version: 1.0
 */
import type { CreateRuleDto, RuleResponseDto, UpdateRuleDto } from '.././';

import { customInstance } from '../../api/mutator';

/**
 * @summary Create a new trading rule
 */
export type rulesControllerCreateResponse201 = {
  data: RuleResponseDto;
  status: 201;
};

export type rulesControllerCreateResponse400 = {
  data: void;
  status: 400;
};

export type rulesControllerCreateResponse401 = {
  data: void;
  status: 401;
};

export type rulesControllerCreateResponseSuccess =
  rulesControllerCreateResponse201 & {
    headers: Headers;
  };
export type rulesControllerCreateResponseError = (
  | rulesControllerCreateResponse400
  | rulesControllerCreateResponse401
) & {
  headers: Headers;
};

export type rulesControllerCreateResponse =
  | rulesControllerCreateResponseSuccess
  | rulesControllerCreateResponseError;

export const getRulesControllerCreateUrl = () => {
  return `/api/v1/rules`;
};

export const rulesControllerCreate = async (
  createRuleDto: CreateRuleDto,
  options?: RequestInit
): Promise<rulesControllerCreateResponse> => {
  return customInstance<rulesControllerCreateResponse>(
    getRulesControllerCreateUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(createRuleDto),
    }
  );
};

/**
 * @summary Get all rules for the authenticated user
 */
export type rulesControllerFindAllResponse200 = {
  data: RuleResponseDto[];
  status: 200;
};

export type rulesControllerFindAllResponse401 = {
  data: void;
  status: 401;
};

export type rulesControllerFindAllResponseSuccess =
  rulesControllerFindAllResponse200 & {
    headers: Headers;
  };
export type rulesControllerFindAllResponseError =
  rulesControllerFindAllResponse401 & {
    headers: Headers;
  };

export type rulesControllerFindAllResponse =
  | rulesControllerFindAllResponseSuccess
  | rulesControllerFindAllResponseError;

export const getRulesControllerFindAllUrl = () => {
  return `/api/v1/rules`;
};

export const rulesControllerFindAll = async (
  options?: RequestInit
): Promise<rulesControllerFindAllResponse> => {
  return customInstance<rulesControllerFindAllResponse>(
    getRulesControllerFindAllUrl(),
    {
      ...options,
      method: 'GET',
    }
  );
};

/**
 * @summary Get a specific rule by ID
 */
export type rulesControllerFindOneResponse200 = {
  data: RuleResponseDto;
  status: 200;
};

export type rulesControllerFindOneResponse401 = {
  data: void;
  status: 401;
};

export type rulesControllerFindOneResponse404 = {
  data: void;
  status: 404;
};

export type rulesControllerFindOneResponseSuccess =
  rulesControllerFindOneResponse200 & {
    headers: Headers;
  };
export type rulesControllerFindOneResponseError = (
  | rulesControllerFindOneResponse401
  | rulesControllerFindOneResponse404
) & {
  headers: Headers;
};

export type rulesControllerFindOneResponse =
  | rulesControllerFindOneResponseSuccess
  | rulesControllerFindOneResponseError;

export const getRulesControllerFindOneUrl = (id: number) => {
  return `/api/v1/rules/${id}`;
};

export const rulesControllerFindOne = async (
  id: number,
  options?: RequestInit
): Promise<rulesControllerFindOneResponse> => {
  return customInstance<rulesControllerFindOneResponse>(
    getRulesControllerFindOneUrl(id),
    {
      ...options,
      method: 'GET',
    }
  );
};

/**
 * @summary Update a rule
 */
export type rulesControllerUpdateResponse200 = {
  data: RuleResponseDto;
  status: 200;
};

export type rulesControllerUpdateResponse400 = {
  data: void;
  status: 400;
};

export type rulesControllerUpdateResponse401 = {
  data: void;
  status: 401;
};

export type rulesControllerUpdateResponse404 = {
  data: void;
  status: 404;
};

export type rulesControllerUpdateResponseSuccess =
  rulesControllerUpdateResponse200 & {
    headers: Headers;
  };
export type rulesControllerUpdateResponseError = (
  | rulesControllerUpdateResponse400
  | rulesControllerUpdateResponse401
  | rulesControllerUpdateResponse404
) & {
  headers: Headers;
};

export type rulesControllerUpdateResponse =
  | rulesControllerUpdateResponseSuccess
  | rulesControllerUpdateResponseError;

export const getRulesControllerUpdateUrl = (id: number) => {
  return `/api/v1/rules/${id}`;
};

export const rulesControllerUpdate = async (
  id: number,
  updateRuleDto: UpdateRuleDto,
  options?: RequestInit
): Promise<rulesControllerUpdateResponse> => {
  return customInstance<rulesControllerUpdateResponse>(
    getRulesControllerUpdateUrl(id),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(updateRuleDto),
    }
  );
};

/**
 * @summary Delete a rule
 */
export type rulesControllerRemoveResponse200 = {
  data: void;
  status: 200;
};

export type rulesControllerRemoveResponse401 = {
  data: void;
  status: 401;
};

export type rulesControllerRemoveResponse404 = {
  data: void;
  status: 404;
};

export type rulesControllerRemoveResponseSuccess =
  rulesControllerRemoveResponse200 & {
    headers: Headers;
  };
export type rulesControllerRemoveResponseError = (
  | rulesControllerRemoveResponse401
  | rulesControllerRemoveResponse404
) & {
  headers: Headers;
};

export type rulesControllerRemoveResponse =
  | rulesControllerRemoveResponseSuccess
  | rulesControllerRemoveResponseError;

export const getRulesControllerRemoveUrl = (id: number) => {
  return `/api/v1/rules/${id}`;
};

export const rulesControllerRemove = async (
  id: number,
  options?: RequestInit
): Promise<rulesControllerRemoveResponse> => {
  return customInstance<rulesControllerRemoveResponse>(
    getRulesControllerRemoveUrl(id),
    {
      ...options,
      method: 'DELETE',
    }
  );
};
