/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Trading Bot API
 * API for trading bot user management and authentication
 * OpenAPI spec version: 1.0
 */
import type { AuthResponseDto, LoginDto } from '.././';

import { customInstance } from '../../api/mutator';

/**
 * @summary User login
 */
export type authControllerLoginResponse200 = {
  data: AuthResponseDto;
  status: 200;
};

export type authControllerLoginResponse401 = {
  data: void;
  status: 401;
};

export type authControllerLoginResponseSuccess =
  authControllerLoginResponse200 & {
    headers: Headers;
  };
export type authControllerLoginResponseError =
  authControllerLoginResponse401 & {
    headers: Headers;
  };

export type authControllerLoginResponse =
  | authControllerLoginResponseSuccess
  | authControllerLoginResponseError;

export const getAuthControllerLoginUrl = () => {
  return `/api/v1/auth/login`;
};

export const authControllerLogin = async (
  loginDto: LoginDto,
  options?: RequestInit
): Promise<authControllerLoginResponse> => {
  return customInstance<authControllerLoginResponse>(
    getAuthControllerLoginUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(loginDto),
    }
  );
};
