/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Trading Bot API
 * API for trading bot user management and authentication
 * OpenAPI spec version: 1.0
 */
import { customInstance } from './mutator';
/**
 * Trading experience level
 */
export type TradingExperienceLevel =
  (typeof TradingExperienceLevel)[keyof typeof TradingExperienceLevel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TradingExperienceLevel = {
  Beginner: 'Beginner',
  Intermediate: 'Intermediate',
  Advanced: 'Advanced',
} as const;

/**
 * Primary trading strategy
 */
export type PrimaryTradingStrategy =
  (typeof PrimaryTradingStrategy)[keyof typeof PrimaryTradingStrategy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PrimaryTradingStrategy = {
  Scalping: 'Scalping',
  DayTrading: 'DayTrading',
  SwingTrading: 'SwingTrading',
  PositionTrading: 'PositionTrading',
  Automated: 'Automated',
} as const;

/**
 * Risk tolerance level
 */
export type RiskTolerance = (typeof RiskTolerance)[keyof typeof RiskTolerance];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RiskTolerance = {
  Conservative: 'Conservative',
  Moderate: 'Moderate',
  Aggressive: 'Aggressive',
} as const;

/**
 * Preferred trading platforms (multiple selection allowed)
 */
export type TradingPlatform =
  (typeof TradingPlatform)[keyof typeof TradingPlatform];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TradingPlatform = {
  Binance: 'Binance',
  Bybit: 'Bybit',
  Kraken: 'Kraken',
  Other: 'Other',
} as const;

export interface CreateUserDto {
  /** Unique nickname for the user */
  nickname: string;
  /** User email address */
  email: string;
  /**
   * User password (must be at least 8 characters, contain uppercase, lowercase, number, and special character)
   * @minLength 8
   */
  password: string;
  /** User first name */
  firstName: string;
  /** User last name */
  lastName: string;
  /** Trading experience level */
  tradingExperienceLevel?: TradingExperienceLevel;
  /** Primary trading strategy */
  primaryTradingStrategy?: PrimaryTradingStrategy;
  /** Risk tolerance level */
  riskTolerance?: RiskTolerance;
  /** Preferred trading platforms (multiple selection allowed) */
  preferredTradingPlatforms?: TradingPlatform[];
}

export interface LoginDto {
  /** User email address */
  email: string;
  /**
   * User password
   * @minLength 6
   */
  password: string;
}

/**
 * User information
 */
export type AuthResponseDtoUser = { [key: string]: unknown };

export interface AuthResponseDto {
  /** JWT access token */
  access_token: string;
  /** User information */
  user: AuthResponseDtoUser;
}

export interface VerifyEmailDto {
  /**
   * 6-digit verification code sent to user email
   * @minLength 6
   * @maxLength 6
   */
  code: string;
  /** Registration token received from user registration */
  token: string;
}

export interface VerifyEmailResponseDto {
  /** Success message */
  message: string;
  /** Indicates if verification was successful */
  success: boolean;
}

/**
 * Rule configuration as JSON object
 */
export type CreateRuleDtoRuleBody = { [key: string]: unknown };

export interface CreateRuleDto {
  /** Name of the trading rule */
  name: string;
  /** Description of what this rule does */
  description: string;
  /** Rule configuration as JSON object */
  ruleBody: CreateRuleDtoRuleBody;
}

/**
 * Rule configuration as JSON object
 */
export type RuleResponseDtoRuleBody = { [key: string]: unknown };

export interface RuleResponseDto {
  /** Unique identifier of the rule */
  id: number;
  /** Name of the trading rule */
  name: string;
  /** Description of what this rule does */
  description: string;
  /** Rule configuration as JSON object */
  ruleBody: RuleResponseDtoRuleBody;
  /** ID of the user who created this rule */
  authorId: number;
}

/**
 * Rule configuration as JSON object
 */
export type UpdateRuleDtoRuleBody = { [key: string]: unknown };

export interface UpdateRuleDto {
  /** Name of the trading rule */
  name?: string;
  /** Description of what this rule does */
  description?: string;
  /** Rule configuration as JSON object */
  ruleBody?: UpdateRuleDtoRuleBody;
}

/**
 * @summary Create a user
 */
export type usersApiControllerCreateUserResponse201 = {
  data: void;
  status: 201;
};

export type usersApiControllerCreateUserResponseSuccess =
  usersApiControllerCreateUserResponse201 & {
    headers: Headers;
  };
export type usersApiControllerCreateUserResponse =
  usersApiControllerCreateUserResponseSuccess;

export const getUsersApiControllerCreateUserUrl = () => {
  return `/api/v1/users`;
};

export const usersApiControllerCreateUser = async (
  createUserDto: CreateUserDto,
  options?: RequestInit
): Promise<usersApiControllerCreateUserResponse> => {
  return customInstance<usersApiControllerCreateUserResponse>(
    getUsersApiControllerCreateUserUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(createUserDto),
    }
  );
};

/**
 * @summary User login
 */
export type authControllerLoginResponse200 = {
  data: AuthResponseDto;
  status: 200;
};

export type authControllerLoginResponse401 = {
  data: void;
  status: 401;
};

export type authControllerLoginResponseSuccess =
  authControllerLoginResponse200 & {
    headers: Headers;
  };
export type authControllerLoginResponseError =
  authControllerLoginResponse401 & {
    headers: Headers;
  };

export type authControllerLoginResponse =
  | authControllerLoginResponseSuccess
  | authControllerLoginResponseError;

export const getAuthControllerLoginUrl = () => {
  return `/api/v1/auth/login`;
};

export const authControllerLogin = async (
  loginDto: LoginDto,
  options?: RequestInit
): Promise<authControllerLoginResponse> => {
  return customInstance<authControllerLoginResponse>(
    getAuthControllerLoginUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(loginDto),
    }
  );
};

/**
 * @summary Verify user email with verification code
 */
export type authControllerVerifyEmailResponse200 = {
  data: VerifyEmailResponseDto;
  status: 200;
};

export type authControllerVerifyEmailResponse400 = {
  data: void;
  status: 400;
};

export type authControllerVerifyEmailResponse401 = {
  data: void;
  status: 401;
};

export type authControllerVerifyEmailResponseSuccess =
  authControllerVerifyEmailResponse200 & {
    headers: Headers;
  };
export type authControllerVerifyEmailResponseError = (
  | authControllerVerifyEmailResponse400
  | authControllerVerifyEmailResponse401
) & {
  headers: Headers;
};

export type authControllerVerifyEmailResponse =
  | authControllerVerifyEmailResponseSuccess
  | authControllerVerifyEmailResponseError;

export const getAuthControllerVerifyEmailUrl = () => {
  return `/api/v1/auth/verify-email`;
};

export const authControllerVerifyEmail = async (
  verifyEmailDto: VerifyEmailDto,
  options?: RequestInit
): Promise<authControllerVerifyEmailResponse> => {
  return customInstance<authControllerVerifyEmailResponse>(
    getAuthControllerVerifyEmailUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(verifyEmailDto),
    }
  );
};

/**
 * @summary Create a new trading rule
 */
export type rulesControllerCreateResponse201 = {
  data: RuleResponseDto;
  status: 201;
};

export type rulesControllerCreateResponse400 = {
  data: void;
  status: 400;
};

export type rulesControllerCreateResponse401 = {
  data: void;
  status: 401;
};

export type rulesControllerCreateResponseSuccess =
  rulesControllerCreateResponse201 & {
    headers: Headers;
  };
export type rulesControllerCreateResponseError = (
  | rulesControllerCreateResponse400
  | rulesControllerCreateResponse401
) & {
  headers: Headers;
};

export type rulesControllerCreateResponse =
  | rulesControllerCreateResponseSuccess
  | rulesControllerCreateResponseError;

export const getRulesControllerCreateUrl = () => {
  return `/api/v1/rules`;
};

export const rulesControllerCreate = async (
  createRuleDto: CreateRuleDto,
  options?: RequestInit
): Promise<rulesControllerCreateResponse> => {
  return customInstance<rulesControllerCreateResponse>(
    getRulesControllerCreateUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(createRuleDto),
    }
  );
};

/**
 * @summary Get all rules for the authenticated user
 */
export type rulesControllerFindAllResponse200 = {
  data: RuleResponseDto[];
  status: 200;
};

export type rulesControllerFindAllResponse401 = {
  data: void;
  status: 401;
};

export type rulesControllerFindAllResponseSuccess =
  rulesControllerFindAllResponse200 & {
    headers: Headers;
  };
export type rulesControllerFindAllResponseError =
  rulesControllerFindAllResponse401 & {
    headers: Headers;
  };

export type rulesControllerFindAllResponse =
  | rulesControllerFindAllResponseSuccess
  | rulesControllerFindAllResponseError;

export const getRulesControllerFindAllUrl = () => {
  return `/api/v1/rules`;
};

export const rulesControllerFindAll = async (
  options?: RequestInit
): Promise<rulesControllerFindAllResponse> => {
  return customInstance<rulesControllerFindAllResponse>(
    getRulesControllerFindAllUrl(),
    {
      ...options,
      method: 'GET',
    }
  );
};

/**
 * @summary Get a specific rule by ID
 */
export type rulesControllerFindOneResponse200 = {
  data: RuleResponseDto;
  status: 200;
};

export type rulesControllerFindOneResponse401 = {
  data: void;
  status: 401;
};

export type rulesControllerFindOneResponse404 = {
  data: void;
  status: 404;
};

export type rulesControllerFindOneResponseSuccess =
  rulesControllerFindOneResponse200 & {
    headers: Headers;
  };
export type rulesControllerFindOneResponseError = (
  | rulesControllerFindOneResponse401
  | rulesControllerFindOneResponse404
) & {
  headers: Headers;
};

export type rulesControllerFindOneResponse =
  | rulesControllerFindOneResponseSuccess
  | rulesControllerFindOneResponseError;

export const getRulesControllerFindOneUrl = (id: number) => {
  return `/api/v1/rules/${id}`;
};

export const rulesControllerFindOne = async (
  id: number,
  options?: RequestInit
): Promise<rulesControllerFindOneResponse> => {
  return customInstance<rulesControllerFindOneResponse>(
    getRulesControllerFindOneUrl(id),
    {
      ...options,
      method: 'GET',
    }
  );
};

/**
 * @summary Update a rule
 */
export type rulesControllerUpdateResponse200 = {
  data: RuleResponseDto;
  status: 200;
};

export type rulesControllerUpdateResponse400 = {
  data: void;
  status: 400;
};

export type rulesControllerUpdateResponse401 = {
  data: void;
  status: 401;
};

export type rulesControllerUpdateResponse404 = {
  data: void;
  status: 404;
};

export type rulesControllerUpdateResponseSuccess =
  rulesControllerUpdateResponse200 & {
    headers: Headers;
  };
export type rulesControllerUpdateResponseError = (
  | rulesControllerUpdateResponse400
  | rulesControllerUpdateResponse401
  | rulesControllerUpdateResponse404
) & {
  headers: Headers;
};

export type rulesControllerUpdateResponse =
  | rulesControllerUpdateResponseSuccess
  | rulesControllerUpdateResponseError;

export const getRulesControllerUpdateUrl = (id: number) => {
  return `/api/v1/rules/${id}`;
};

export const rulesControllerUpdate = async (
  id: number,
  updateRuleDto: UpdateRuleDto,
  options?: RequestInit
): Promise<rulesControllerUpdateResponse> => {
  return customInstance<rulesControllerUpdateResponse>(
    getRulesControllerUpdateUrl(id),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(updateRuleDto),
    }
  );
};

/**
 * @summary Delete a rule
 */
export type rulesControllerRemoveResponse200 = {
  data: void;
  status: 200;
};

export type rulesControllerRemoveResponse401 = {
  data: void;
  status: 401;
};

export type rulesControllerRemoveResponse404 = {
  data: void;
  status: 404;
};

export type rulesControllerRemoveResponseSuccess =
  rulesControllerRemoveResponse200 & {
    headers: Headers;
  };
export type rulesControllerRemoveResponseError = (
  | rulesControllerRemoveResponse401
  | rulesControllerRemoveResponse404
) & {
  headers: Headers;
};

export type rulesControllerRemoveResponse =
  | rulesControllerRemoveResponseSuccess
  | rulesControllerRemoveResponseError;

export const getRulesControllerRemoveUrl = (id: number) => {
  return `/api/v1/rules/${id}`;
};

export const rulesControllerRemove = async (
  id: number,
  options?: RequestInit
): Promise<rulesControllerRemoveResponse> => {
  return customInstance<rulesControllerRemoveResponse>(
    getRulesControllerRemoveUrl(id),
    {
      ...options,
      method: 'DELETE',
    }
  );
};
