/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Trading Bot API
 * API for trading bot user management and authentication
 * OpenAPI spec version: 1.0
 */
/**
 * Trading experience level
 */
export type TradingExperienceLevel =
  (typeof TradingExperienceLevel)[keyof typeof TradingExperienceLevel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TradingExperienceLevel = {
  Beginner: 'Beginner',
  Intermediate: 'Intermediate',
  Advanced: 'Advanced',
} as const;

/**
 * Primary trading strategy
 */
export type PrimaryTradingStrategy =
  (typeof PrimaryTradingStrategy)[keyof typeof PrimaryTradingStrategy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PrimaryTradingStrategy = {
  Scalping: 'Scalping',
  DayTrading: 'DayTrading',
  SwingTrading: 'SwingTrading',
  PositionTrading: 'PositionTrading',
  Automated: 'Automated',
} as const;

/**
 * Risk tolerance level
 */
export type RiskTolerance = (typeof RiskTolerance)[keyof typeof RiskTolerance];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RiskTolerance = {
  Conservative: 'Conservative',
  Moderate: 'Moderate',
  Aggressive: 'Aggressive',
} as const;

/**
 * Preferred trading platforms (multiple selection allowed)
 */
export type TradingPlatform =
  (typeof TradingPlatform)[keyof typeof TradingPlatform];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TradingPlatform = {
  Binance: 'Binance',
  Bybit: 'Bybit',
  Kraken: 'Kraken',
  Other: 'Other',
} as const;

export interface CreateUserDto {
  /** Unique nickname for the user */
  nickname: string;
  /** User email address */
  email: string;
  /**
   * User password (must be at least 8 characters, contain uppercase, lowercase, number, and special character)
   * @minLength 8
   */
  password: string;
  /** User first name */
  firstName: string;
  /** User last name */
  lastName: string;
  /** Trading experience level */
  tradingExperienceLevel?: TradingExperienceLevel;
  /** Primary trading strategy */
  primaryTradingStrategy?: PrimaryTradingStrategy;
  /** Risk tolerance level */
  riskTolerance?: RiskTolerance;
  /** Preferred trading platforms (multiple selection allowed) */
  preferredTradingPlatforms?: TradingPlatform[];
}

export interface LoginDto {
  /** User email address */
  email: string;
  /**
   * User password
   * @minLength 6
   */
  password: string;
}

/**
 * User information
 */
export type AuthResponseDtoUser = { [key: string]: unknown };

export interface AuthResponseDto {
  /** JWT access token */
  access_token: string;
  /** User information */
  user: AuthResponseDtoUser;
}

/**
 * Rule configuration as JSON object
 */
export type CreateRuleDtoRuleBody = { [key: string]: unknown };

export interface CreateRuleDto {
  /** Name of the trading rule */
  name: string;
  /** Description of what this rule does */
  description: string;
  /** Rule configuration as JSON object */
  ruleBody: CreateRuleDtoRuleBody;
}

/**
 * Rule configuration as JSON object
 */
export type RuleResponseDtoRuleBody = { [key: string]: unknown };

export interface RuleResponseDto {
  /** Unique identifier of the rule */
  id: number;
  /** Name of the trading rule */
  name: string;
  /** Description of what this rule does */
  description: string;
  /** Rule configuration as JSON object */
  ruleBody: RuleResponseDtoRuleBody;
  /** ID of the user who created this rule */
  authorId: number;
}

/**
 * Rule configuration as JSON object
 */
export type UpdateRuleDtoRuleBody = { [key: string]: unknown };

export interface UpdateRuleDto {
  /** Name of the trading rule */
  name?: string;
  /** Description of what this rule does */
  description?: string;
  /** Rule configuration as JSON object */
  ruleBody?: UpdateRuleDtoRuleBody;
}
