/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Trading Bot API
 * API for trading bot user management and authentication
 * OpenAPI spec version: 1.0
 */
import type { AuthResponseDtoUser } from './authResponseDtoUser';

export interface AuthResponseDto {
  /** JWT access token */
  access_token: string;
  /** User information */
  user: AuthResponseDtoUser;
}
