/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Trading Bot API
 * API for trading bot user management and authentication
 * OpenAPI spec version: 1.0
 */

/**
 * User information
 */
export type AuthResponseDtoUser = { [key: string]: unknown };
