/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Trading Bot API
 * API for trading bot user management and authentication
 * OpenAPI spec version: 1.0
 */
import type { TradingExperienceLevel } from './tradingExperienceLevel';
import type { PrimaryTradingStrategy } from './primaryTradingStrategy';
import type { RiskTolerance } from './riskTolerance';
import type { TradingPlatform } from './tradingPlatform';

export interface CreateUserDto {
  /** Unique nickname for the user */
  nickname: string;
  /** User email address */
  email: string;
  /**
   * User password (must be at least 8 characters, contain uppercase, lowercase, number, and special character)
   * @minLength 8
   */
  password: string;
  /** User first name */
  firstName: string;
  /** User last name */
  lastName: string;
  /** Trading experience level */
  tradingExperienceLevel?: TradingExperienceLevel;
  /** Primary trading strategy */
  primaryTradingStrategy?: PrimaryTradingStrategy;
  /** Risk tolerance level */
  riskTolerance?: RiskTolerance;
  /** Preferred trading platforms (multiple selection allowed) */
  preferredTradingPlatforms?: TradingPlatform[];
}
