/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Trading Bot API
 * API for trading bot user management and authentication
 * OpenAPI spec version: 1.0
 */

export interface LoginDto {
  /** User email address */
  email: string;
  /**
   * User password
   * @minLength 6
   */
  password: string;
}
