/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Trading Bot API
 * API for trading bot user management and authentication
 * OpenAPI spec version: 1.0
 */

/**
 * Primary trading strategy
 */
export type PrimaryTradingStrategy =
  (typeof PrimaryTradingStrategy)[keyof typeof PrimaryTradingStrategy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PrimaryTradingStrategy = {
  Scalping: 'Scalping',
  DayTrading: 'DayTrading',
  SwingTrading: 'SwingTrading',
  PositionTrading: 'PositionTrading',
  Automated: 'Automated',
} as const;
