/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Trading Bot API
 * API for trading bot user management and authentication
 * OpenAPI spec version: 1.0
 */

/**
 * Risk tolerance level
 */
export type RiskTolerance = (typeof RiskTolerance)[keyof typeof RiskTolerance];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RiskTolerance = {
  Conservative: 'Conservative',
  Moderate: 'Moderate',
  Aggressive: 'Aggressive',
} as const;
