/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Trading Bot API
 * API for trading bot user management and authentication
 * OpenAPI spec version: 1.0
 */
import type { RuleResponseDtoRuleBody } from './ruleResponseDtoRuleBody';

export interface RuleResponseDto {
  /** Unique identifier of the rule */
  id: number;
  /** Name of the trading rule */
  name: string;
  /** Description of what this rule does */
  description: string;
  /** Rule configuration as JSON object */
  ruleBody: RuleResponseDtoRuleBody;
  /** ID of the user who created this rule */
  authorId: number;
}
