/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Trading Bot API
 * API for trading bot user management and authentication
 * OpenAPI spec version: 1.0
 */

/**
 * Preferred trading platforms (multiple selection allowed)
 */
export type TradingPlatform =
  (typeof TradingPlatform)[keyof typeof TradingPlatform];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TradingPlatform = {
  Binance: 'Binance',
  Bybit: 'Bybit',
  Kraken: 'Kraken',
  Other: 'Other',
} as const;
