/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Trading Bot API
 * API for trading bot user management and authentication
 * OpenAPI spec version: 1.0
 */

/**
 * Trading experience level
 */
export type TradingExperienceLevel =
  (typeof TradingExperienceLevel)[keyof typeof TradingExperienceLevel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TradingExperienceLevel = {
  Beginner: 'Beginner',
  Intermediate: 'Intermediate',
  Advanced: 'Advanced',
} as const;
