/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Trading Bot API
 * API for trading bot user management and authentication
 * OpenAPI spec version: 1.0
 */
import type { UpdateRuleDtoRuleBody } from './updateRuleDtoRuleBody';

export interface UpdateRuleDto {
  /** Name of the trading rule */
  name?: string;
  /** Description of what this rule does */
  description?: string;
  /** Rule configuration as JSON object */
  ruleBody?: UpdateRuleDtoRuleBody;
}
