class ObjectNavigator {
  
  private data: any = {};
  
  constructor(data?: any) {
    this.data = data ?? {};
  }

  /**
   * Add description
   * @param key 
   * @param value 
   * @param current 
   * @returns 
   */
  static setValue (key: string, value: any, current: { [key: string]: any } | any[] & { [key: string]: any }){ // TODO check this type

    const isArrayKey = /^\[\d*\]$/.test(key);

    if(!isArrayKey){

      if(Array.isArray(current)){
        throw new Error("Can't set property to an array");  
      }

      current[key] = value;
      return;
    }

    if(!Array.isArray(current)){
      throw new Error("Can't set array to not array");
    }

    if(key === '[]'){
      current.push(value);
      return;
    }

    const match = key.match(/\d+/);
    if (match === null) {
      throw new Error("Invalid array index");
    }

    const index = parseInt(match[0], 10);
    current[index] = value;

  }

  /**
   * Add description
   * @param currentKey 
   * @param nextKey 
   * @param current 
   * @returns 
   */
  static switchCreateCurrent(currentKey: string, nextKey: string, current: { [key: string]: any } | any[] & { [key: string]: any }){

    const isCurrentKeyArrayElement = /^\[\d*\]$/.test(currentKey);
    const isNextKeyArrayElement = /^\[\d*\]$/.test(nextKey);

    if(!isCurrentKeyArrayElement){

      if(Array.isArray(current)){
        throw new Error("Can't set property to an array")
      }
      
      if(current.hasOwnProperty(currentKey)){
        return current[currentKey];
      }

      current[currentKey] = isNextKeyArrayElement ? [] : {};
      return current[currentKey];

    }
    // Work with current Array
    if(!Array.isArray(current)){
      throw new Error("Can't set array to not array");
    } 

    if(currentKey === '[]'){
      const next = isNextKeyArrayElement ? [] : {};
      current.push(next);
      return current[current.length -1];
    }

    const match = currentKey.match(/\d+/);
    if (match === null) {
      throw new Error("Invalid array syntax");
    }

    const index = parseInt(match[0], 10);
    if(current[index] === undefined){
      throw new Error("Index does not exist");
    };
    return current[index];
  }

  /**
   * Add description
   * @param key 
   * @param data 
   * @returns 
   */
  set(key: string, data: any) {

    const keys: string[] = key.split('.');
    let current = this.data;
    
    for (let i = 0; i < keys.length; i++) {

      const isLastIteration = i === keys.length - 1;
      const currentKey: string = keys[i];

      if(isLastIteration){
        ObjectNavigator.setValue(currentKey, data, current);
        return;
      }

      const nextKey = keys[i + 1];

      current = ObjectNavigator.switchCreateCurrent(currentKey, nextKey, current);

    }
  }

  /**
   * Add description
   * @param key 
   * @param defaultValue 
   * @returns 
   */
  get(key: string, defaultValue?: any): any {
    const keys = key.split('.');
    let current = this.data;

    for (const k of keys) {
      // TODO probably we want to return null. Think about this
      if (current == null) { // null or undefined
        return defaultValue;
      }

      if(Array.isArray(current) && k === '[]'){
        current = current[current.length - 1];
        continue;
      }

      if(Array.isArray(current) && /^\[-?\d+\]$/.test(k)){
        const stringIndex = k.replace(/\[|\]/g, "");
        let index = parseInt( stringIndex, 10 );
        if(index < 0){
          index = index + current.length;
        }
        current = current[index];
        continue;
      }

      if (typeof current === 'object') {
        current = current[k];
        continue;
      }
        
      return defaultValue;
      
    }

    return current !== undefined ? current : defaultValue;
  }

  /**
   * 
   * @param key Add description
   * @returns 
   */
  delete(key: string){

    // TODO check this method. All code generated by `copilot`.
    const keys = key.split('.');
    let current = this.data;

    for (let i = 0; i < keys.length - 1; i++) {
      if (current == null) {
        return;
      }

      const currentKey = keys[i];
      if (Array.isArray(current) && /^\[-?\d+\]$/.test(currentKey)) {
        const stringIndex = currentKey.replace(/\[|\]/g, "");
        let index = parseInt(stringIndex, 10);
        if (index < 0) {
          index = index + current.length;
        }
        current = current[index];
      } else {
        current = current[currentKey];
      }
    }

    const lastKey = keys[keys.length - 1];
    if (Array.isArray(current) && /^\[-?\d+\]$/.test(lastKey)) {
      const stringIndex = lastKey.replace(/\[|\]/g, "");
      let index = parseInt(stringIndex, 10);
      if (index < 0) {
        index = index + current.length;
      }
      current.splice(index, 1);
    } else {
      delete current[lastKey];
    }

  }

}

export default ObjectNavigator
